name: Teste Jobs in Gihub Actions

on:
  push:
    branches:
      - main
    
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Create file
      run: |
        echo 'Olá mundo!' > teste.txt

    - name: Show file
      run: |
        cat teste.txt
  job2:
    runs-on: ubuntu-latest

    steps:
    - name: Show file
      run: |
        cat teste.txt
